packages:
  - '.'

allowBuilds:
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@ttoss/geovis@0.2.0 || 0.19.1 || 0.19.4'
  - '@ttoss/geovis-workspace@0.11.1 || 0.13.0'

patchedDependencies:
  '@ttoss/geovis@0.19.4': patches/@ttoss__geovis@0.19.4.patch
